name: Main CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install OpenMP (macOS only)
        if: runner.os == 'macOS'
        run: brew install libomp
      - name: Nightly
        run: |
          rustup toolchain install nightly --component clippy
          rustup override set nightly
      - name: Clippy
        run: cargo clippy -- -Dwarnings
      - name: Build
        run: cargo build  -vv
      - name: Build with features
        run: cargo build -vv --all-features
      - name: Run tests
        run: cargo test
      - name: Run tests with features
        run: cargo test --all-features
